name: Release DEV
on:
  push:
    branches:
      - master
jobs:
  Release-DEV:
    runs-on: ubuntu-20.04
    steps:
      - name: Prepare Variables
        id: vars
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          IMAGE="n8nny/coinint-api"
          echo ::set-output name=tagged_image::${IMAGE}:${TAG}
          echo ::set-output name=tag::${TAG}

      - uses: actions/checkout@v2

      # Docker build & Push 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build and push 
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: '${{ steps.vars.outputs.tagged_image }}'
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move Docker cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Check out my other private repo
        uses: actions/checkout@v3
        with:
          repository: forward-wallet/IAC
          path: infrastructure
          token: ${{ secrets.GH_PAT }}

      - name: Update Coinint API Image Version in deployment
        uses: fjogeleit/yaml-update-action@main
        with:
          changes: |
            {
              "kubernetes/forward-dev/intnode/coinint-api/deployment.yml": {
                ".spec.template.spec.containers[0].image": "${{ steps.vars.outputs.tagged_image }}"
              }            
            }
          branch: main
          createPR: false
          commitChange: true
          message: ':rocket:[DEV]Update coinint API Version to ${{ steps.vars.outputs.tag }}'
          workDir: infrastructure
          repository: forward-wallet/IAC
          token: ${{ secrets.GH_PAT }}

